version: '3.8'

services:
  killbill:
    network_mode: host
    image: killbill/killbill:0.24.0
    environment:
      - KILLBILL_CATALOG_URI=SpyCarAdvanced.xml
      - KILLBILL_DAO_URL=jdbc:postgresql://127.0.0.1:5432/killbill
      - KILLBILL_DAO_USER=postgres
      - KILLBILL_DAO_PASSWORD=postgres
      - KILLBILL_SERVER_TEST_MODE=true
      - KILLBILL_INVOICE_SANITY_SAFETY_BOUND_ENABLED=false
      - KILLBILL_INVOICE_MAX_DAILY_NUMBER_OF_ITEMS_SAFETY_BOUND=-1
    depends_on:
      - db
  db:
    network_mode: host
    image: killbill/postgresql:0.24
    environment:
      - POSTGRES_PASSWORD=postgres
